version: '3.8'

services:
  slack-bot:
    build: .
    container_name: Message-listener-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    networks:
      - bot-network
  
  redis:
    image: redis:7-alpine
    container_name: master-listener-redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - bot-network

volumes:
  redis-data:

networks:
  bot-network:
    driver: bridge 
